### ISSUE TITLE
Failed to set mediaType

### ISSUE THREAD

**Issue by PaulaScharf** [snavas/GECCO#15]
On the new PC sometimes GECCO throws this error:
```[ WARN:0] global C:\projects\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (676) CvCapture_MSMF::initStream Failed to set mediaType (stream 0, (640x480 @ 30) MFVideoFormat_RGB24(codec not found)

Process finished with exit code -1073741819 (0xC0000005)
```

Currently the 415 camera always throws this error while the 435 only spontaneously throws it. 

Sometimes it helps to change the USB port of the camera.

Downgrading Vidgear to 0.1.8 did not fix the issue.

**Comment by snavas** [comment]
Maybe updating the cameras firmware to their latest stable version is solving this issue.

**Comment by PaulaScharf** [comment]
fixed but we dont know how
