### ISSUE TITLE
Error in cv::convexityDefects using cv2 4.4.0.46

### ISSUE THREAD

**Issue by snavas** [snavas/GECCO#3]
The convex hull indices are not monotonous, which can be in the case when the input contour contains self-intersections in function 'cv::convexityDefects'

In the meantime using cv2 `4.2.0.34` is recommended

This bug/unexpected behaviour starts happening since cv2 version`4.3.0.36` 

```
pip install opencv-contrib-python==4.2.0.34
```

**Comment by snavas** [comment]
Applying cv2 [morphological transformations](https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_imgproc/py_morphological_ops/py_morphological_ops.html) like erode and/or dilate might avoid the problem but would worsen the hand features recognition.

e.g. in

https://github.com/snavas/GECCO/blob/master/tests/testHand.py#L123

```python
thresholded = cv2.erode(thresholded, kernel, iterations=1)
thresholded = cv2.dilate(thresholded, kernel, iterations=1)
```

Sorting the hull indices might be a better alternative:

https://github.com/opencv/opencv/issues/4539#issuecomment-766798290

**Comment by snavas** [comment]
Sorting the hull indices might prove to be a better solution: https://github.com/opencv/opencv/issues/4539#issuecomment-766798290

e.g. adding:
https://github.com/snavas/GECCO/blob/3b3d43c363e4359ec2844a31651da411937d52b5/tests/testHand.py#L154-L155
```python
hull[::-1].sort(axis=0)
index[::-1].sort(axis=0)
```

But, it also appears to worsen hand recognition.

**Comment by PaulaScharf** [comment]
It tested it as well and the number of detected hands seems to stay roughly the same. How did you notice that it worsens the hand recognition?

**Comment by snavas** [comment]
> It tested it as well and the number of detected hands seems to stay roughly the same. How did you notice that it worsens the hand recognition?

I did a quick test before and it avoided the error but the indexes weren't correctly sorted. But, at first glance I would say your solution works perfectly!
